#!/usr/bin/bash
# CALL:    compile_article filename.tex
# RETURNS: filename.pdf

# get filename without .tex extension
filename=${1%.*}
bibname=$filename".bib"

# if there is a bibliography .bib file called $bibname, then:
if [ -e "$bibname" ]; then
    pdflatex $filename
    bibtex $filename
    pdflatex $filename
    pdflatex $filename
    echo
    echo "... Compiled LaTeX file w/ BiBTeX citations to "$filename".pdf"
# if the .bib file does not exist:
else
    pdflatex $filename
    echo
    echo "... Compiled standard LaTeX file to "$filename".pdf"
fi

# if clean_up_files is already in ~/bin:
clean_up_files
# if clean_up_files is not in the bin, and is only in this directory:
# ./clean_up_files
